name: Test

on:
  pull_request:
    branches:
      - master
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js v17.3.0
      uses: actions/setup-node@v1
      with:
        node-version: '17.3.0'
    - run: yarn install
    - run: yarn run test